FROM python:3.11-slim 

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    sudo \
    file \
    procps \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /notebooks

COPY requirements.txt . 
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt 
   

COPY notebooks/ .

COPY notebooks/entrypoint.sh /notebooks/entrypoint.sh
RUN chmod +x /notebooks/entrypoint.sh


CMD ["/notebook/entrypoint.sh"]